### ISSUE TITLE
Error with th current version of Metamath

### ISSUE THREAD

**Issue by amelieled** [tirix/set-noov.mm#1]
This repository seems to be outdated:
```
?Error: "$( Begin $[..." without matching "$( End $[..."
?Error: file "set-pred.mm" (included in "MM-DATA/Extra/RAW/set-noov.mm") was no
t found
?Error: "$( Begin $[..." without matching "$( End $[..."
?Source was not read due to error(s).  Please correct and try again.
MM> 
```

**Comment by tirix** [comment]
Indeed the `set-class` and `set-main` sections were opened but never closed.
[0a5e69e](https://github.com/tirix/set-noov.mm/commit/0a5e69e5d8c22b73428956a08ae08884a2bb07e4) should fix that, thanks for reporting!
